name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.5.6
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.0.5
  firebase_auth: 4.1.0
  firebase_core: ^2.2.0
  meta: ^1.3.0
  flutter_chat_types:
    git:
      url: https://github.com/amsyary/flutter_chat_types.git
      ref: 8512211967d82a6ea6218740a5839e239fd1970a
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
