name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.5.2
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter_chat_types:
    git: https://github.com/amsyary/flutter_chat_types.git
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
